### ISSUE TITLE
The WebSocket is currently Closed

### ISSUE THREAD

**Issue by vdksystem** [justdjango/django_chat#65]
Tried to follow tutorial and got "The WebSocket is currently Closed" on the first run
In the console I see that Django constantly reloads on changes (despite there is no changes)

Cloned this repo to ensure I don't have errors in code, but the same result

Run on Mac, with docker-compose

**Comment by rez0n** [comment]
Hi @vdksystem 
Faced with same issue, then I noticed that I have no such line on runserver starting
```
Starting ASGI/Channels version 3.0.5 development server at ..
```

but have 
```
Starting development server at ...
```

which means regular WSGI handler started instead ASGI.
I looked at channels 4.0.0 release notes and noticed that a lot things has been changed since previous release 3.0.5 which is used for this particular tutorial.
As I understand you need add `daphne` package to the installed apps (and also install `attrs` package for it) or downgrade to channels@3.0.5
I've chosen second way and it works.
